### ISSUE TITLE
1994 and 1996 are missing their Century in the YEAR column

### ISSUE THREAD

**Issue by paulgronke** [Reed-EVIC/cpsvote#12]
In the cps data, 1994 and 1996 are saved as "94" and "96" in the YEAR column.

**Comment by jayleetx** [comment]
Yes - this is a pre-Y2K artifact of the raw CPS data. When you run `cps_label`, there's an argument `expand_year = TRUE` that will fix this.

I've set it up this way in an attempt to read in the "original" CPS data, typos and all, and THEN apply some editorial discretion.

**Comment by paulgronke** [comment]
I would override this even though this is the "original" data. I never even realized!

**Comment by jayleetx** [comment]
Closing for now since we left this peculiarity in for the package release.
