### ISSUE TITLE
Unable to read 2018 into memory

### ISSUE THREAD

**Issue by paulgronke** [Reed-EVIC/cpsvote#13]
When attempting to read any combination of years that includes 2018 into memory, this error kicks out:

```
Error in if (grepl("\n", file)) { : argument is of length zero
In addition: Warning message:
In utils::unzip(file, exdir = temp) :

```

I suspect this is because 2018 is a "gz" and not a "zip" file.

**Comment by jayleetx** [comment]
Did this improve after updating? Right now it's working on my machine

**Comment by jayleetx** [comment]
The update did fix this, but I have re-framed the problem in #15
