### ISSUE TITLE
You must run cps_label before cps_recode_vote

### ISSUE THREAD

**Issue by paulgronke** [Reed-EVIC/cpsvote#14]
I see why this is done this way, but what if a user does not want to make everything factors, but still wants to do the vote recode and weighting? Should that be allowed?

**Comment by jayleetx** [comment]
That makes sense - right now both functions are pretty hard-coded for the "YES"/"NO" factors, but at some point soon I can rewrite the to take numeric entries as well.

And if we want to make it possible to do these in either order (`label %>% recode %>% reweight` or `recode %>% reweight %>% label`), then we'll need to add the recoded votes into the `cps_factors` data set. to make sure that they don't get left as numeric when everything else gets labeled
