### ISSUE TITLE
Legacy Data

### ISSUE THREAD

**Issue by jayleetx** [Reed-EVIC/cpsvote#2]
Currently the package only supports data since the year 1994. This is as much as [NBER](http://data.nber.org/data/current-population-survey-data.html) hosts, so anything before then would have to come from an alternative source (ICPSR, etc.). @paulgronke mentioned that the data before this year is not typically used, but I've forgotten the reason.

In short- is it worth supporting this older VRS data?

Additionally - there's a major change in data format in 1996, so 1994 isn't super comparable to any other year covered afterwards. If we're excluding pre-1994, is it worth writing all the code to wrangle 1994 to mesh with 1996 onwards?

**Comment by paulgronke** [comment]
I don’t think anyone uses the data prior to 1994.

---
Paul Gronke
Professor, Reed College
Director, Early Voting Information Center
http://earlyvoting.net

General Inquiries: Jay lee jaylee@reed.edu

Media Inquiries: Kevin Myers myersk@reed.edu

**Comment by jayleetx** [comment]
For now we're sticking with 1994 onwards.
