### ISSUE TITLE
Turnout variable as currently calculated is incorrect, need three versions

### ISSUE THREAD

**Issue by paulgronke** [Reed-EVIC/cpsvote#8]
I think `VRS_VOTE` is incorrectly coded. 

Right now, the version we have doesn't correspond to either usage, and that needs to be fixed because our turnout estimates are incorrect. 

**PES1**
|RAW PES1     |   CPS Turnout  |  "Hur Achen" Turnout|
---------|----------------|-----------------
|-9  No response | Not Voted | NA |
|-3 Refused | Not voted | NA |
|-2 DK | Not voted | NA |
|-1 Not in universe | NA | NA |
|1 Yes Voted | Voted | Voted |
|2 Not Voted | Not Voted | Not Voted |

I would like three turnout variables:

1. *PES1* in raw, untransformed form
2. *VRS_VOTE* coded following the second column above. This will track the CPS reports from their website. 
3. *HA_VOTE* which is the Hur-Achen coding. This will not correspond to *anything* but is needed as a placeholder to calculate a new weight. We can deal with that once we have the corrected turnout variable.

**Comment by jayleetx** [comment]
This is initially addressed, see further discussion in #14
