### ISSUE TITLE
save raw data files as alternative to recoded data

### ISSUE THREAD

**Issue by paulgronke** [Reed-EVIC/cpsvote#9]
Currently CPSVOTE conducts a series of transformations, factoring, etc directly on the individual CPS data sets, before they are then merged.

This leaves the user no way to check on the results of CPS vote against the original, untransformed data, or to perform any statistical calculations on the raw data.

For the subset of variables that we include in our package, it would be valuable to be able to either always have, or have an option, to save raw data  (with only the key variables -- not all variables) perhaps in the "cps_data" directory? Alternatively, we could allow a user to specify something like "raw = TRUE" which will append the original, untransformed data columns onto the final output data set.

**Comment by jayleetx** [comment]
This is accomplished now in `cps_read`, which just reads in the raw numeric data. The argument `names_col = "cps_name"` will also read the original CPS column names, and throw a warning to remind you that columns change over time
